export { default as LandingPage } from "./Landing-page/LandingPage";
export { default as Task } from "./FAQ/Tasks/Tasks";
export { default as Premium } from "./FAQ/Premium/Premium";
export { default as Account } from "./FAQ/Account/Account";
export { default as Contact } from "./Contact/Contact";
export { default as PrivatePolicy } from "./Privacy/PrivatePolicy";
export { default as FAQ } from "./FAQ/LowerLevel";
export { default as About } from "./About/About";
export { default as Career } from "./Career/Career";
